# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tN5vIG1IiCuRzx3csUyeXp9CJ9jjVAHi
"""

name = input('enter your name')
print('whats your name? ,' + name)
